# Site settings
title:               Floor 5, Floor 6
tagline:             在五楼与六楼之间爬上爬下的程序猿
description:         '五楼，六楼……'
baseurl:             /                          # the subpath of your site, e.g. /blog/
url:                 https://f5f6.github.io

# Build settings
permalink:           /:year/:month/:day/:title/

markdown:            kramdown
highlighter:         rouge
kramdown:
  auto_ids: true
  toc_levels: 1..4
  syntax_highlighter: rouge
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  enable_coderay: true

  syntax_highlighter_opt:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

paginate:            3

# Custom variables
github:
  repo:              https://github.com/f5f6