# Site settings
title: Floor 5, Floor 6
#email: your-email@domain.com
description: 在五楼与六楼之间爬上爬下的程序猿
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://f5f6.github.io"

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..3

gems:
- jekyll-mentions